### PR TITLE
added symbols for diode bridges 

### PR DESCRIPTION
**Pull request by jkriege2**

### CODE REVIEW

**Comment by jkriege2** [comment]
b1

**Comment by pointhi** [comment]
Please fix KLC:

```
checking module: Diode_Bridge_32x5.7
  Violating Rule 6.3
    For through-hole components, footprint anchor is set on pad 1.
  Violating Rule 6.5
    Silkscreen is not superposed to pads, its outline is completely visible after board assembly, uses
    0.15mm line width and provides a reference mark for pin 1. (IPC-7351).
  Violating Rule 6.6
    Courtyard line has a width 0.05mm. This line is placed so that its clearance is measured from its
    center to the edges of pads and body, and its position is rounded on a grid of 0.05mm.
    No courtyard line found in the module
checking module: Diode_Bridge_32x5.7_-WW+
  Violating Rule 6.3
    For through-hole components, footprint anchor is set on pad 1.
  Violating Rule 6.5
    Silkscreen is not superposed to pads, its outline is completely visible after board assembly, uses
    0.15mm line width and provides a reference mark for pin 1. (IPC-7351).
  Violating Rule 6.6
    Courtyard line has a width 0.05mm. This line is placed so that its clearance is measured from its
    center to the edges of pads and body, and its position is rounded on a grid of 0.05mm.
    No courtyard line found in the module
```

**Comment by pointhi** [comment]
* Please add Fabrication layer
* I need a datasheet to check the component
* rotate component 180 degree (pin 1 should be on the left side according to KLC)

**Comment by jkriege2** [comment]
datasheets:
  - http://cdn-reichelt.de/documents/datenblatt/A400/B40C5000-3300B.pdf
  - http://cdn-reichelt.de/documents/datenblatt/A400/BXXC5000-3X00A.pdf

KLCs check out fine for both with me now ... all other things should be fixed with the last commit

Best,
JAN

**Comment by evanshultz** [comment]
@SchrodingersGat @poeschlr Can you close and re-open to trigger Travis?

**Comment by evanshultz** [comment]
Thanks Rene!

@jkriege2 When you get back, are you able to finish off this PR?

**Comment by jkriege2** [comment]
I think I will close it and in some weeks time push a set of different rectifier housings in proper style and KLC ;-)

JAN

**Pull request closed without merging**
