### PR TITLE
Add DO-34 packages and DO-35 (horizontal RM7.5/7.62mm and vertical RM2.54mm)

### PR DESCRIPTION
**Pull request by jkriege2**
diodes

### CODE REVIEW

**Comment by jkriege2** [comment]
added 3d models with this com
dau
dau_sod81
dku
dku_sod81



mit:
https://github.com/KiCad/kicad-library/pull/709

**Comment by pointhi** [comment]
Please fix KLC:

```
checking module: Diode_DO-34_SOD68_Horizontal_RM10
  Violating Rule 10.3
  Violating Rule 6.3
  Violating Rule 6.5
  Violating Rule 6.6
checking module: Diode_DO-34_SOD68_Horizontal_RM5
  Violating Rule 10.3
  Violating Rule 6.3
  Violating Rule 6.5
  Violating Rule 6.6
checking module: Diode_DO-34_SOD68_Horizontal_RM7.5
  Violating Rule 10.3
  Violating Rule 6.3
  Violating Rule 6.5
  Violating Rule 6.6
checking module: Diode_DO-34_SOD68_Vertical_AnodeUp_RM2.54
  Violating Rule 10.3
  Violating Rule 6.3
  Violating Rule 6.5
  Violating Rule 6.6
checking module: Diode_DO-34_SOD68_Vertical_KathodeUp_RM2.54
  Violating Rule 10.3
  Violating Rule 6.3
  Violating Rule 6.5
  Violating Rule 6.6
checking module: Diode_DO-35_SOD27_Horizontal_RM10
  Violating Rule 10.3
  Violating Rule 6.3
  Violating Rule 6.6
checking module: Diode_DO-35_SOD27_Horizontal_RM7.5
  Violating Rule 10.3
  Violating Rule 10.7
  Violating Rule 6.3
  Violating Rule 6.5
  Violating Rule 6.6
checking module: Diode_DO-35_SOD27_Horizontal_RM7.62
  Violating Rule 10.3
  Violating Rule 10.7
  Violating Rule 6.3
  Violating Rule 6.5
  Violating Rule 6.6
checking module: Diode_DO-35_SOD27_Vertical_AnodeUp_RM2.54
  Violating Rule 10.3
  Violating Rule 6.3
  Violating Rule 6.5
  Violating Rule 6.6
checking module: Diode_DO-35_SOD27_Vertical_KathodeUp_RM2.54
  Violating Rule 10.3
  Violating Rule 6.3
  Violating Rule 6.5
  Violating Rule 6.6
checking module: Diode_DO-41_SOD81_Vertical_AnodeUp
  Violating Rule 10.3
  Violating Rule 6.6
checking module: Diode_DO-41_SOD81_Vertical_KathodeUp
  Violating Rule 10.3
  Violating Rule 6.6
```

**Comment by pointhi** [comment]
* Please fix courtjard distance (read KLC)
* add Fabrication layer

**Comment by jkriege2** [comment]
done!

JAN

**Pull request closed without merging**
