### PR TITLE
Add WOB Diode Bridge

### PR DESCRIPTION
**Pull request by pointhi**
source: http://www.farnell.com/datasheets/62619.pdf

diode_wob

The Footprint is KLC complicant, but I'm not sure about pin numbering.

Currently, the pin numbering is the same as defined in the `Diode_Bridge` symbol in the library. But normaly pin 1 is used reference edge and not pin 3. Also I'm not sure for the naming scheme. Probably `Diode_Bridge_W0x` is a better naming scheme. (I didn't found a real clear naming scheme for this package)

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
@pointhi  I think that _W0B is ok for the suffix. Does the datasheet indicate PIN1 anywhere? Or is 1="+" assumed for diode bridges?

**Comment by pointhi** [comment]
currently 3 is considered as + in the schematic. Probably this has to be changed (which would be more logical in my eyes, but then we would also need to change the footprints accordingly)

**Comment by SchrodingersGat** [comment]
Hi @pointhi this one has been lurking for a while - sorry about that! If you want to continue on this please update to meet new KLC and we can merge! Thanks!

**Comment by evanshultz** [comment]
@SchrodingersGat @poeschlr Can you close and re-open to trigger Travis?

**Comment by evanshultz** [comment]
@pointhi Are you able to address the remaining issues so this PR can be merged? The current symbol library (thanks Jan!) has a number of bridge rectifier pinouts, the 4th of which will work for this footprint:
image

**Comment by SchrodingersGat** [comment]
Hi @pointhi are you going to address this? It'd be nice to get this PR finalised and merged :)

**Comment by SchrodingersGat** [comment]
@pointhi if you want to continue with this, please resubmit to https://github.com/kicad/kicad-footprints thanks :)

**Pull request closed without merging**
